// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List PixelCraft printing products (mugs, t-shirts, photo books, prints, gifts) with names, categories, and PKR prices.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. 'mugs', 't-shirts'."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    let q = supabase.from("products").select("*").limit(limit ?? 50);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single PixelCraft product by id, including its SEO/AEO/GEO metadata when available.",
  inputSchema: {
    id: z2.string().min(1).describe("Product id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("products").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/site-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var site_info_default = defineTool3({
  name: "site_info",
  title: "PixelCraft site info",
  description: "Return brand, contact, categories, and support info for PixelCraft \u2014 a custom printing store in Pakistan.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            brand: "PixelCraft",
            country: "Pakistan",
            currency: "PKR",
            categories: ["mugs", "t-shirts", "photo-books", "photo-prints", "gifts"],
            support: { whatsapp: "+92 42 3334442957" },
            paymentMethods: ["COD", "Bank transfer", "Local gateways"]
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pixelcraft-mcp",
  title: "PixelCraft MCP",
  version: "0.1.0",
  instructions: "Tools for PixelCraft, a custom printing store in Pakistan. Use `site_info` for brand/support details, `list_products` to browse the catalog (optionally filter by category), and `get_product` to fetch one product with its SEO metadata. All prices are in PKR.",
  tools: [site_info_default, list_products_default, get_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
